import type { Experience } from "../_types/experience";

export const experiences: Array<Experience> = [
  {
    role: "Software Engineer (Part-time)",
    company: "LINE MAN Wongnai",
    logoUrl: "https://avatars.githubusercontent.com/u/108649272",
    type: "Part-time",
    location: "Bangkok, Thailand",
    startDate: "2025-08-01",
    endDate: null,
    description:
      "Designing service integrations and BFF services to enable seamless data exchange across platforms.",
    achievements: [
      "Designed and developed service integrations across LINE MAN Wongnai platforms, enabling seamless data exchange between internal systems",
      "Defined API specifications and implemented Backend-for-Frontend (BFF) services using Go to support mobile and web clients",
      "Implemented MQTT-based real-time communication between iOS applications and backend services to support live updates and event-driven features",
      "Collaborated with cross-functional teams to ensure scalability, reliability, and performance of production systems",
    ],
    tags: [
      "Go",
      "MQTT",
      "System Integration",
      "API Design",
      "Real-time",
      "iOS",
      "Monorepo",
    ],
    isCurrent: true,
  },
  {
    role: "Software Engineer Intern (iOS)",
    company: "LINE MAN Wongnai",
    logoUrl: "https://avatars.githubusercontent.com/u/108649272",
    description:
      "Developed a Reservation Service for FoodStory POS, integrated Capacitor for WebView usage, and built a customer-facing reservation website using Vite and React.",
    startDate: "2025-05-01",
    endDate: "2025-08-01",
    achievements: [
      "Designed and developed a Reservation Service for FoodStory POS, supporting merchant-side booking workflows",
      "Integrated Capacitor to enable seamless WebView usage within native iOS applications",
      "Built a customer-facing reservation website using Vite and React, focusing on performance and usability",
      "Implemented CI/CD pipelines using GitLab CI and deployed services via ArgoCD following GitOps practices",
    ],
    tags: [
      "iOS",
      "Swift",
      "React",
      "Vite",
      "Capacitor",
      "CI/CD",
      "GitOps",
      "POS Systems",
      "WebView",
    ],
    isCurrent: false,
  },
  {
    role: "Senior Vice President, Research & Development",
    company: "OpenMirai Corporation",
    logoUrl: "https://avatars.githubusercontent.com/u/78855212",
    type: "Full-time",
    location: "Hybrid",
    startDate: "2025-01-01",
    endDate: null,
    description:
      "Leading technical strategy and platform evolution across frontend, backend, and infrastructure teams.",
    achievements: [
      "Led the architecture and development of a frontend monorepo using React and Turbopack, supporting multiple production applications",
      "Designed and built backend APIs in Go, adopting microservices architecture for scalability and maintainability",
      "Established containerized deployment workflows using Docker and Kubernetes, with continuous delivery managed via ArgoCD",
      "Drove technical strategy, platform evolution, and engineering best practices across frontend, backend, and infrastructure teams",
    ],
    tags: [
      "React",
      "Go",
      "Kubernetes",
      "Microservices",
      "System Design",
      "Docker",
      "Monorepo",
      "Leadership",
      "DevOps",
    ],
    isCurrent: true,
  },
  {
    role: "Co-Founder",
    company: "inedible.dev",
    logoUrl: "https://avatars.githubusercontent.com/u/70066296",
    type: "Community",
    location: "Remote",
    startDate: "2020-01-01",
    endDate: null,
    description:
      "Building a community-driven initiative for innovative open-source solutions.",
    achievements: [
      "Co-founded a community-driven software initiative focused on building innovative, reliable, and open-source solutions",
      "Designed, developed, and maintained open-source applications adopted by developers and organizations",
      "Deployed and operated cloud-based services, ensuring production-grade reliability and maintainability",
      "Fostered a collaborative engineering culture centered on knowledge sharing and long-term sustainability",
    ],
    tags: [
      "Open Source",
      "Community Building",
      "Cloud Ops",
      "Engineering Culture",
    ],
    isCurrent: true,
  },
  {
    role: "HPC-AI Specialist (Apprenticeship)",
    company: "NSTDA Supercomputer Center (ThaiSC)",
    startDate: "2024-07-01",
    endDate: "2024-09-01",
    description:
      "Developed and optimized software workflows for Large Language Models (LLMs) in high-performance computing environments.",
    achievements: [
      "Developed and optimized software workflows for Large Language Models (LLMs) in high-performance computing environments",
      "Applied HPC optimization techniques, including GPU acceleration with CUDA and performance-oriented shell scripting",
      "Worked with large-scale compute infrastructure to improve training and inference efficiency for AI workloads",
    ],
    tags: [
      "HPC",
      "LLMs",
      "CUDA",
      "Python",
      "Linux",
      "AI",
      "GPU Computing",
      "Shell Scripting",
    ],
    isCurrent: false,
  },
];
